// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization;
using SpacetimeDB.BSATN;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message : IStructuralReadWrite
    {
        [DataMember(Name = "Sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "Sent")]
        public SpacetimeDB.Timestamp Sent;
        [DataMember(Name = "Text")]
        public string Text;

        public Message(
            SpacetimeDB.Identity Sender,
            SpacetimeDB.Timestamp Sent,
            string Text
        )
        {
            this.Sender = Sender;
            this.Sent = Sent;
            this.Text = Text;
        }

        public Message()
        {
            this.Text = "";
        }

        public void ReadFields(BinaryReader reader) {
            Sender = SpacetimeDB.Identity.FromHexString(reader.ReadString());
            Sent = SpacetimeDB.Timestamp.FromTimeSpanSinceUnixEpoch(new TimeSpan(0, 0, 0, 0, reader.ReadInt32()));
            Text = reader.ReadString();
        }
        public void WriteFields(BinaryWriter writer) {
            writer.Write(Sender.ToString());
            writer.Write(Sent.ToTimeSpanSinceUnixEpoch().Microseconds);
            writer.Write(Text);
        }
    }
}
