// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization;
using SpacetimeDB.BSATN;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User : IStructuralReadWrite {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Name")]
        public string? Name;
        [DataMember(Name = "Online")]
        public bool Online;

        public User(
            SpacetimeDB.Identity Identity,
            string? Name,
            bool Online
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Online = Online;
        }

        public User()
        {
        }

        public void ReadFields(BinaryReader reader) {
            this.Identity = SpacetimeDB.Identity.FromHexString(reader.ReadString());
            this.Name = reader.ReadBoolean() ? reader.ReadString() : null;
            this.Online = reader.ReadBoolean();
        }
        public void WriteFields(BinaryWriter writer) {
            writer.Write(Identity.ToString());
            writer.Write(Name == null ? false : true);
            if (Name != null) {
                writer.Write(Name);
            }
            writer.Write(Online);
        }
    }
}
